# Generated by Django 3.2.11 on 2022-01-08 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('is_voucher_needed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TravelExpenseArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mime_type', models.CharField(max_length=64)),
                ('data', models.FileField(upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=3, max_digits=20)),
                ('paid', models.BooleanField()),
                ('remarks', models.CharField(blank=True, max_length=256, null=True)),
                ('business_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='travel_expense.businesstrip')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.currency')),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travel_expense.expensetype')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='travel_expense.file')),
            ],
        ),
        migrations.CreateModel(
            name='DailyAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=20)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.currency')),
                ('grade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.grade')),
            ],
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travel_expense.destination'),
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ApprovalRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=20)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.currency')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.grade')),
                ('travelExpenseArea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travel_expense.travelexpensearea')),
            ],
        ),
    ]
