# Generated by Django 4.0 on 2021-12-19 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('latitude', models.DecimalField(decimal_places=17, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=17, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='TravelExpenseArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.user')),
            ],
        ),
        migrations.CreateModel(
            name='Expence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=3, max_digits=20)),
                ('paid', models.BooleanField()),
                ('remarks', models.CharField(max_length=256)),
                ('business_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_expense.businesstrip')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.currency')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travel_expense.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='DailyAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=20)),
                ('classification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.classification')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.currency')),
            ],
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travel_expense.destination'),
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.user'),
        ),
        migrations.CreateModel(
            name='ApprovalRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_user', to='system.user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.user')),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=20)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.classification')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.currency')),
                ('travelExpenseArea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travel_expense.travelexpensearea')),
            ],
        ),
    ]
