# Generated by Django 4.0 on 2022-01-02 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_expense', '0004_alter_travelexpensearea_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='travel_expense.receipt'),
        ),
        migrations.AlterField(
            model_name='expence',
            name='remarks',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
