# Generated by Django 4.0 on 2022-01-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_country_country_flag_alter_country_latitude_and_more'),
        ('travel_expense', '0005_alter_expence_receipt_alter_expence_remarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expence',
            new_name='Expense',
        ),
    ]
