# Generated by Django 4.0 on 2022-01-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_expense', '0006_rename_expence_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='business_trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='travel_expense.businesstrip'),
        ),
    ]
