# Generated by Django 4.0 on 2022-01-06 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_expense', '0007_alter_expense_business_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('is_voucher_needed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='travel_expense.expensetype'),
            preserve_default=False,
        ),
    ]
