# Generated by Django 4.0 on 2021-12-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Required', max_length=254, verbose_name='email address'),
        ),
    ]
