# Generated by Django 4.0 on 2021-12-25 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.department'),
        ),
    ]
